import {useEffect,useState} from "react";
import {api,type Config,type Job} from "./api";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Button} from "./components/ui/button";import {Input} from "./components/ui/input";import {Label} from "./components/ui/label";import {Badge} from "./components/ui/badge";import {Switch} from "./components/ui/switch";import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "./components/ui/select";import "./theme.css";
const priorities:Record<string,string>={none:"未设置",low:"低",medium:"中",high:"高",critical:"紧急"};const levels:Record<string,string>={low:"低",normal:"普通",high:"高",critical:"最高"};
const states:Record<string,string>={scheduled:"待发送",retry_wait:"等待重试",sending:"发送中",gateway_accepted:"已提交推送",expired:"已过期",superseded:"安排已替换",cancelled:"已取消",failed:"发送失败"};const kinds:Record<string,string>={start:"开始提醒",due:"截止提醒",created:"创建提醒"};
const defaults:Config={enabled:false,gateway_url:"",channel_id:"",channel_name:"",timezone:"Asia/Shanghai",start_minutes:10,due_minutes:10,created_push:false,checkin_enabled:false,priority_map:{none:"normal",low:"low",medium:"normal",high:"high",critical:"critical"}};
export default function SettingsTab({projectId,canEdit=true}:{projectId:string;canEdit?:boolean}){
 const path=`/projects/${encodeURIComponent(projectId)}`;const [config,setConfig]=useState(defaults);const [revision,setRevision]=useState(0);const [password,setPassword]=useState("");const [jobs,setJobs]=useState<Job[]>([]);const [message,setMessage]=useState("正在读取提醒设置…");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const [s,q]=await Promise.all([api<{config:Config;revision:number;last_error?:string}>(path+"/settings"),api<{items:Job[]}>(path+"/jobs")]);setConfig({...defaults,...s.config});setRevision(s.revision);setJobs(q.items);setMessage(s.config.enabled?"项目提醒已启用":"项目提醒未启用");setError(s.last_error?"提醒暂未完成，请检查频道或打卡安排后重试。":"")}
 useEffect(()=>{load().catch(()=>setError("暂时无法读取，请稍后重试。"))},[path]);
 function change<K extends keyof Config>(key:K,value:Config[K]){setConfig(c=>({...c,[key]:value}))}
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"操作未完成，请稍后重试。") }finally{setBusy(false)}}
 const date=(v:string)=>new Intl.DateTimeFormat("zh-CN",{timeZone:config.timezone,dateStyle:"short",timeStyle:"short"}).format(new Date(v));
 return <div className="checkin-ui grid gap-5"><Card><CardHeader><CardTitle>PushGo 提醒</CardTitle><CardDescription role="status">{message}</CardDescription></CardHeader><CardContent className="grid gap-5">{error&&<p role="alert" className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}
 <Label className="flex justify-between">启用项目提醒<Switch checked={config.enabled} onCheckedChange={v=>change("enabled",v)} disabled={!canEdit}/></Label>
 <Label className="grid gap-2">推送服务地址<Input placeholder="https://push.example.org" value={config.gateway_url} onChange={e=>change("gateway_url",e.target.value)}/></Label>
 <div className="grid gap-4 sm:grid-cols-2"><Label className="grid gap-2">频道标识<Input value={config.channel_id} onChange={e=>change("channel_id",e.target.value)}/></Label><Label className="grid gap-2">频道名称<Input value={config.channel_name} onChange={e=>change("channel_name",e.target.value)}/></Label></div>
 <Label className="grid gap-2">频道密码<Input type="password" autoComplete="new-password" placeholder="留空保留已保存的密码" value={password} onChange={e=>setPassword(e.target.value)}/></Label>
 <div className="grid gap-4 sm:grid-cols-3"><Label className="grid gap-2">时区<Input value={config.timezone} onChange={e=>change("timezone",e.target.value)}/></Label><Label className="grid gap-2">开始提前（分钟）<Input type="number" min="0" max="1440" value={config.start_minutes} onChange={e=>change("start_minutes",Number(e.target.value))}/></Label><Label className="grid gap-2">截止提前（分钟）<Input type="number" min="0" max="1440" value={config.due_minutes} onChange={e=>change("due_minutes",Number(e.target.value))}/></Label></div>
 <div className="grid gap-4 rounded-xl border p-4"><Label className="flex justify-between">创建任务时立即提醒<Switch checked={config.created_push} onCheckedChange={v=>change("created_push",v)}/></Label><Label className="flex justify-between">在提醒中提供拍照打卡<Switch checked={config.checkin_enabled} onCheckedChange={v=>change("checkin_enabled",v)}/></Label><p className="text-sm text-muted-foreground">启用打卡前，请先在拍照打卡设置中确认状态和时间。提醒将使用对应的打卡安排。</p></div>
 <div className="grid gap-3"><h3 className="text-sm font-medium">任务优先级与通知等级</h3><div className="grid gap-3 sm:grid-cols-5">{Object.entries(config.priority_map).map(([key,value])=><Label key={key} className="grid gap-2">{priorities[key]??"自定义"}<Select value={value} onValueChange={v=>change("priority_map",{...config.priority_map,[key]:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(levels).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select></Label>)}</div></div>
 <div className="flex flex-wrap gap-3"><Button disabled={busy||!canEdit} onClick={()=>run(async()=>{await api(path+"/settings","PUT",{...config,revision,...(password?{password}:{})});setPassword("");await load();setMessage("设置已保存")})}>保存提醒设置</Button><Button variant="outline" disabled={busy} onClick={()=>run(load)}>刷新</Button></div><p className="text-sm text-muted-foreground">任务需要准确到时分才能安排提醒。任务改期、完成、归档或删除后，会更新尚未发送的提醒。</p></CardContent></Card>
 <Card><CardHeader><CardTitle>最近提醒</CardTitle><CardDescription>已提交推送表示服务已接收，手机送达情况以实际通知为准。</CardDescription></CardHeader><CardContent className="grid gap-3">{jobs.length===0?<p className="text-sm text-muted-foreground">暂无提醒安排</p>:jobs.map(j=><div key={j.id} className="grid gap-2 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><a className="font-medium text-primary" href={`/projects/${projectId}/tasks/${j.task_id}`}>{j.title||"任务提醒"}</a><Badge variant={j.state==="failed"?"destructive":"secondary"}>{states[j.state]??"处理中"}</Badge></div><dl className="grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">提醒类型</dt><dd>{kinds[j.kind]??"任务提醒"}</dd></div><div><dt className="text-muted-foreground">发送时间</dt><dd>{date(j.fire_at)}</dd></div><div><dt className="text-muted-foreground">有效截止</dt><dd>{date(j.expires_at)}</dd></div>{j.attempts>1&&<div><dt className="text-muted-foreground">发送次数</dt><dd>{j.attempts}</dd></div>}</dl>{j.error&&<p className="text-sm text-muted-foreground">发送尚未完成，请检查频道与任务安排。</p>}{["failed","retry_wait"].includes(j.state)&&<Button variant="outline" className="w-fit" disabled={busy||!canEdit} onClick={()=>run(async()=>{await api(`${path}/jobs/${j.id}/retry`,"POST",{});await load()})}>重试提醒</Button>}</div>)}</CardContent></Card></div>
}
