import {Input} from "./components/ui/input";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "./components/ui/select";
export type TimeValue={precision:"none"|"day"|"instant";value:string};
export type TaskTimes={start:TimeValue;due:TimeValue;timezone:string;start_minutes:number;due_minutes:number};
export const emptyTimes=():TaskTimes=>({start:{precision:"none",value:""},due:{precision:"none",value:""},timezone:"Asia/Shanghai",start_minutes:10,due_minutes:10});
export function localValue(value:string,zone:string){if(!value||!/(Z|[+-]\d\d:\d\d)$/.test(value))return value.slice(0,16);try{return new Intl.DateTimeFormat("sv-SE",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value)).replace(" ","T")}catch{return ""}}
export default function TaskTimesForm({value,onChange,disabled=false}:{value:TaskTimes;onChange:(v:TaskTimes)=>void;disabled?:boolean}){
 return <fieldset disabled={disabled} className="grid gap-4 min-w-0"><label className="grid gap-2 text-sm">时区<Input value={value.timezone} placeholder="Asia/Shanghai" onChange={e=>onChange({...value,timezone:e.target.value})}/></label><div className="grid gap-4 sm:grid-cols-2">{(["start","due"] as const).map(key=><div key={key} className="grid content-start gap-3 rounded-lg border p-3"><label className="grid gap-2 text-sm">{key==="start"?"开始时间":"结束时间"}<Select disabled={disabled} value={value[key].precision} onValueChange={v=>onChange({...value,[key]:{precision:v,value:""}})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">未设置</SelectItem><SelectItem value="day">仅日期</SelectItem><SelectItem value="instant">具体时间</SelectItem></SelectContent></Select></label>{value[key].precision!=="none"&&<Input aria-label={key==="start"?"开始日期与时间":"结束日期与时间"} type={value[key].precision==="day"?"date":"datetime-local"} step={60} value={value[key].precision==="instant"?localValue(value[key].value,value.timezone):value[key].value} onChange={e=>onChange({...value,[key]:{...value[key],value:e.target.value}})}/>}<label className="grid gap-2 text-sm">提前提醒（分钟）<Input type="number" min={0} max={1440} value={value[key==="start"?"start_minutes":"due_minutes"]} onChange={e=>onChange({...value,[key==="start"?"start_minutes":"due_minutes"]:Number(e.target.value)})}/></label></div>)}</div><p className="text-sm text-muted-foreground">拍照打卡需提前至少1分钟提醒，建议10分钟；0分钟仅用于普通提醒。</p>{value.start.precision!=="instant"&&value.due.precision!=="instant"&&<p className="text-sm text-muted-foreground">尚未安排定时提醒。设置具体时间后可按时提醒。</p>}</fieldset>;
}
