import {useEffect,useState} from "react";
import {api,request} from "./api";
import {Card,CardHeader,CardTitle,CardContent} from "./components/ui/card";
import {Button} from "./components/ui/button";import {Input} from "./components/ui/input";import {Textarea} from "./components/ui/textarea";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "./components/ui/select";
import TaskTimesForm,{emptyTimes} from "./TaskTimesForm";import {waitOperation,operationKey} from "./task-operations";import "./theme.css";
export default function TimedTaskPage({projectId}:{projectId:string}){
 const [title,setTitle]=useState("");const [content,setContent]=useState("");const [tags,setTags]=useState("");const [importance,setImportance]=useState("35");const [status,setStatus]=useState("");const [statuses,setStatuses]=useState<{id:string;name:string}[]>([]);const [times,setTimes]=useState(emptyTimes);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [pending,setPending]=useState(()=>localStorage.getItem(operationKey(projectId))||"");
 useEffect(()=>{request<{data:{items:{id:string;name:string}[]}}>(`/api/v1/projects/${projectId}/task-statuses`).then(r=>{setStatuses(r.data.items);setStatus(r.data.items[0]?.id||"")}).catch(e=>setError(e.message))},[projectId]);
 async function submit(){setBusy(true);setError("");try{let op=pending;let body:unknown;if(!op){op=crypto.randomUUID();body={op_id:op,kind:"create",title,content,status_id:status,importance:Number(importance),tags:tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean),times};localStorage.setItem(operationKey(projectId)+":body",JSON.stringify(body));localStorage.setItem(operationKey(projectId),op);setPending(op);}else{const saved=localStorage.getItem(operationKey(projectId)+":body");if(saved)body=JSON.parse(saved);}if(body)await api(`/projects/${projectId}/task-operations`,"POST",body);const r=await waitOperation(projectId,op);localStorage.removeItem(operationKey(projectId));localStorage.removeItem(operationKey(projectId)+":body");setPending("");window.location.assign(`/projects/${projectId}/tasks/${r.task_id||r.result?.task_id}`)}catch(e){if(typeof e==="object"&&e!==null&&"status" in e&&[400,401,403,422].includes(Number(e.status))){localStorage.removeItem(operationKey(projectId));localStorage.removeItem(operationKey(projectId)+":body");setPending("")};setError(e instanceof Error?e.message:"任务暂时无法保存。")}finally{setBusy(false)}}

 return <div className="checkin-ui mx-auto w-full max-w-3xl p-3 sm:p-6"><Card><CardHeader><CardTitle>新建定时任务</CardTitle><p className="text-sm text-muted-foreground">填写任务和准确时间，按计划接收提醒。</p></CardHeader><CardContent className="grid gap-5"><fieldset disabled={busy||!!pending} className="grid gap-4 min-w-0"><label className="grid gap-2 text-sm">任务标题<Input value={title} maxLength={1000} onChange={e=>setTitle(e.target.value)}/></label><label className="grid gap-2 text-sm">任务内容<Textarea value={content} rows={5} onChange={e=>setContent(e.target.value)}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">状态<Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-2 text-sm">优先级<Select value={importance} onValueChange={setImportance}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[["0","未设置"],["10","低"],["35","普通"],["75","高"],["150","紧急"]].map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select></label></div><label className="grid gap-2 text-sm">标签<Input placeholder="多个标签用逗号分隔" value={tags} onChange={e=>setTags(e.target.value)}/></label><TaskTimesForm value={times} onChange={setTimes} disabled={busy||!!pending}/></fieldset>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy||!pending&&!title.trim()} onClick={submit}>{busy?"正在保存…":pending?"查询保存结果":"创建任务"}</Button></CardContent></Card></div>;
}
